#!/usr/bin/env python3

import os
import subprocess

from distutils.sysconfig import get_python_lib

HOME = os.path.expanduser("~")
DEVNULL = open(os.devnull, 'w')
CTAGS_FILE = HOME + "/tags"
PATHS = [
    get_python_lib(),
    HOME + "/algolia",
    HOME + "/go/src"
]

def main():
    open(CTAGS_FILE, 'w').close()

    for path in PATHS:
        print("Generating tags for " + path + "...")
        cmd = list(iter(("ctags -R -a -f " + CTAGS_FILE + " " + path).split()))
        subprocess.call(cmd, stderr=DEVNULL)

if __name__ == "__main__":
    main()
