return {
	{
		"nvim-treesitter/nvim-treesitter",
		dependencies = {
			"nvim-treesitter/nvim-treesitter-textobjects",
			branch = "main",
		},
		branch = "main",
		lazy = false,
		build = ":TSUpdate",
		config = function()
			-- https://tduyng.com/blog/neovim-highlight-syntax/
			require("nvim-treesitter").setup({})

			local inc_sel = require("config.incremental-selection")
			vim.keymap.set("v", "v", inc_sel.increment, { desc = "Increment treesitter selection" })
			vim.keymap.set("v", "V", inc_sel.decrement, { desc = "Decrement treesitter selection" })
			require("nvim-treesitter").install({
				"asm",
				"awk",
				"bash",
				"bash",
				"c",
				"caddy",
				"cmake",
				"comment",
				"cpp",
				"css",
				"csv",
				"diff",
				"dockerfile",
				"dot",
				"editorconfig",
				"eex",
				"elixir",
				"erlang",
				"git_config",
				"git_rebase",
				"gitattributes",
				"gitcommit",
				"gitignore",
				"go",
				"gomod",
				"gosum",
				"gotmpl",
				"gowork",
				"gpg",
				"heex",
				"helm",
				"html",
				"html_tags",
				"http",
				"java",
				"javadoc",
				"javascript",
				"jq",
				"jsdoc",
				"json",
				"jsx",
				"lua",
				"luadoc",
				"make",
				"markdown",
				"markdown_inline",
				"mermaid",
				"nginx",
				"pem",
				"po",
				"properties",
				"python",
				"query",
				"regex",
				"robot",
				"robots_txt",
				"rust",
				"sql",
				"ssh_config",
				"templ",
				"terraform",
				"tsx",
				"typescript",
				"vim",
				"vimdoc",
				"xml",
				"yaml",
				"zsh",
			})
		end,
	},
}
